### ISSUE TITLE
Keep prompts when starting Elgato

### ISSUE THREAD

**Issue by Asparthar** [f00d4tehg0dz/elgato-streamdeck-ai-paints#1]
Hi, 

The plugin always resets to default prompts when starting the software. Is there any way to change that? In way I don't have to write all my preferred prompts?

Thank you!

**Comment by f00d4tehg0dz** [comment]
Great suggestion! I'll fix that as soon as I can!

**Comment by f00d4tehg0dz** [comment]
Hey @Asparthar I've made it my top priority this weekend to have this finished. Took a while to figure out how to cache an image. But I got it working. I'll send it off to Elgato shortly

**Comment by Asparthar** [comment]
Thank you for your time!

**Comment by f00d4tehg0dz** [comment]
@Asparthar I've submitted it to the Elgato team. 🎉 It should _hopefully_ be out today or tomorrow in the store as they are based on the West Coast.  If you want to install a non-updatable version you can use this release below. 
https://github.com/f00d4tehg0dz/elgato-streamdeck-ai-paints/releases/tag/1.0.3

Have a good one and thanks for submitting this enhancement! If you think of anything else, please let me know.
